# This is a "normal" job.
universe = vanilla

# Files to place stdout and stderr
output = output/process_$(Cluster)_$(Process).out
error = error/process_$(Cluster)_$(Process).err
log = log/process_$(Cluster)_$(Process).log
#+IsBuildJob = true
#requirements = (Target.HasGluster == true) && (OpSysAndVer =?= "SL6") && (IsBuildSlot == true)
requirements = (Target.HasGluster == true) && (OpSysAndVer =?= "SL6") 

# Copy environment variables from the submit node
getenv = True
environment = "PATH=/bin:/usr/bin:/usr/local/bin LD_LIBRARY_PATH= PYTHONPATH="

# Indicate if/when files should be transfered
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# Indicate the executable to be run and any other input files needed
executable = /home/mouginot/htc_script/mure_run_tar_send.bash
transfer_input_files = /home/mouginot/htc_script/install_mcnp_mure_data_PSPEC.bash, /home/mouginot/htc_script/std_setup.bash, /home/mouginot/htc_script/load.bash, /home/mouginot/PWR_MOX_PSEC.tar.gz, /home/mouginot/.ssh/.netrc, input/$(comp_file)

encrypt_input_files = .ssh/.netrc

# Command line arguments for the executable
arguments = $(comp_file)

# Don't send emails
notification = never

# Request resources
request_cpus = 1
request_memory = 400MB
request_disk = 30GB

queue comp_file from input_list.txt
